#include "init_idt.h"

/*init_idt.c
 *This function takes care of possible interrupts
 *I only focused on division by zero and page fault
 */

/* Divide Error Exception Handler */
void divide_error_exception() {
	cli();
	puts("Cannot Divide by Zero"); // Divisor operand is 0. Invalid operatoin
}

void debug_exception() {
	puts("Debug Exception dectected"); // Debug-exception condition detected.
}

void nmi_interrupt() {
	puts("Nonmaskable interrupt generated"); // Assertion of processor's non-maskable interrupt requested
}

void breakpoint_exception() {
	puts("breakpoint instruction executed"); // Breakpoint trap generated by INT 3
}

void overflow_exception() {
	puts("INTO instruction executed"); // OF flag which indicates overflow trap detected by INTO instruction
}

void bound_exception() {
	cli();
	puts("Bound-range-exceeded"); // Array index is not within the bounds of the array. BOUND-range-exceeded fault generated
}

void invalid_opcode_exception() {
	puts("Invalid opcode executed"); // Invalid or reserved opcode is executed
}

void device_not_available_exception() {
	puts("Device unavailable"); // Either x87 FPU floatin-point is executed while EM flag is set or WAIT?FWAIT instruction is executed while TS and MP flags are set
}

void double_fault_exception() {
	puts("second exception detected"); // Second exception is detected during the execution of exception handler
}

void coprocessor_segment_overrun() {
	puts("coprocessor segment overrun"); // A page or a segment is violated during Intel 387 math coprocessor operation
}

void invalid_TSS_exception() {
	puts("Invalid TSS exception"); // Task state segment related error detected 
}

void segment_not_present() {
	puts("Segmentation fault"); // The present flag of a segment or gate descriptor is found clear
}

void stack_fault_exception() {
	puts("Stack violation happened");  // Stack related limit violation or non-present stack segment detected
}

void general_protection_exception() {
	puts("general protection violation dectected"); // General protection violation is detected by the processor
}

/* Page Fault Exception Handler */
void page_fault_exception() {
	cli();
	puts("Page Fault Exception"); // Exception condition is detected while the paging is enabled
}

void floating_point_error() {
	puts("floating error detected"); // Floatin-point error is detected by the x87 FPU
}

void alignment_check_exception() {
	puts("alignment check exception"); // Unaligned memory operand is detected while the alignment checking is enabled
}

void machine_check_exception() {
	puts("machine check exception"); // Internal machine error or a bus error is detected by the processor
}

void simd_coprocessor_error() {
	puts("simd coprocessor error"); // SSE/SSE2/SSE3 SIMD floating-point exception is detected by the processor
}
